name: Deploy Next.js App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1  # Disable telemetry

      - name: Prepare build directory
        run: |
          mkdir -p build
          cp -r .next public package.json package-lock.json build/
          # Copy config file if exists
          [ -f next.config.mjs ] && cp next.config.mjs build/ || echo "No next.config.mjs found"

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          # Add server to known_hosts
          ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key \
             -o BatchMode=yes \
             ${{ secrets.SERVER_USERNAME }}@${{ secrets.SSH_SERVER_IP }} \
             "echo 'SSH connection successful!'"

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/deploy.yml -i ansible/hosts \
            --extra-vars "ansible_host=${{ secrets.SSH_SERVER_IP }} ansible_user=${{ secrets.SERVER_USERNAME }}" \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"